import React, {useEffect, useMemo, useRef, useState} from 'react';
import {Sun, Moon, LayoutDashboard, Users, ClipboardPenLine, FileText, Upload, Plus, Save, Download, ChevronDown, ChevronLeft, School, Bot, CheckCircle2, AlertCircle, X, LogOut, Cloud, CloudOff, Edit2, ShieldCheck, Clock3, Eye, UserMinus, RotateCcw, Trash2} from 'lucide-react';
import {sampleSchool,parseSchoolWorkbook,calcStats,calcRanks,ROBOT_TYPES} from '../model';
import {supabase,isSupabaseConfigured} from '../supabase';
import {loadSchoolIndex,loadSchoolDetail,loadDashboardInsights,saveSchoolMeta,saveSessionRows,saveClassroomStudents,saveResultRows,saveSchoolBundle,deleteSchool,loadCurrentProfile,loadAccessAdmin,updateUserAccess,saveStudentOrder,loadOffices,createOffice} from '../dataService';
import brandLogo from '../assets/logo.png';
import Select from '../components/ui/Select';

function Dashboard({stats,classes,school,schools,offices,onSelectSchool,onDeleteOffice}){
 const summarizeSchool=s=>{if(s.summary)return s.summary;const results=s.classrooms.flatMap(c=>{const latest=s.sessions.filter(x=>x.classId===c.id).at(-1);return c.students.filter(st=>st.active!==false).map(st=>({...st,...(latest?.entries?.[st.id]||{})}))}),scored=results.filter(st=>!st.absent&&st.score!==''&&st.score!=null&&Number.isFinite(Number(st.score)));return {rooms:s.classrooms.length,students:results.length,scored:scored.length,passed:scored.filter(st=>Number(st.score)>=35).length,scoreTotal:scored.reduce((sum,st)=>sum+Number(st.score),0)}};
 const officeCards=[...offices.map(office=>({id:office.id,name:office.name,schools:schools.filter(s=>s.officeId===office.id)})),...(schools.some(s=>!s.officeId)?[{id:'unassigned',name:'ยังไม่ระบุสำนักงาน',schools:schools.filter(s=>!s.officeId)}]:[])].map(group=>{
  const summaries=group.schools.map(summarizeSchool),rooms=summaries.reduce((sum,x)=>sum+x.rooms,0),students=summaries.reduce((sum,x)=>sum+x.students,0),scored=summaries.reduce((sum,x)=>sum+x.scored,0),passed=summaries.reduce((sum,x)=>sum+x.passed,0),scoreTotal=summaries.reduce((sum,x)=>sum+x.scoreTotal,0);
  return {...group,rooms,students,avg:scored?scoreTotal/scored:0,rate:scored?passed/scored*100:0};
 });
 const overallSummaries = schools.map(summarizeSchool);
 const overallSchools = schools.length;
 const overallStudents = overallSummaries.reduce((sum, x) => sum + x.students, 0);
 const overallScored = overallSummaries.reduce((sum, x) => sum + x.scored, 0);
 const overallPassed = overallSummaries.reduce((sum, x) => sum + x.passed, 0);
 const overallScoreTotal = overallSummaries.reduce((sum, x) => sum + x.scoreTotal, 0);
 const overallAvg = overallScored ? overallScoreTotal / overallScored : 0;
 const overallRate = overallScored ? overallPassed / overallScored * 100 : 0;
 const [selectedOfficeId,setSelectedOfficeId]=useState(null),[dashboardView,setDashboardView]=useState('offices');
 const [insightOffice,setInsightOffice]=useState(''),[insights,setInsights]=useState({attention:[],outstanding:[],roomsToImprove:[],recent:[]}),[insightLoading,setInsightLoading]=useState(true),[insightError,setInsightError]=useState('');
 useEffect(()=>{let active=true;setInsightLoading(true);setInsightError('');loadDashboardInsights(insightOffice||null,20).then(data=>{if(active)setInsights(data)}).catch(error=>{console.error(error);if(active)setInsightError('ยังไม่ได้ติดตั้งฟังก์ชันสรุป Dashboard กรุณารัน schema.sql ใน Supabase')}).finally(()=>{if(active)setInsightLoading(false)});return()=>{active=false}},[insightOffice]);
 useEffect(()=>{if(dashboardView!=='offices'){const officeId=school?.officeId||'unassigned';if(officeCards.some(x=>x.id===officeId))setSelectedOfficeId(officeId)}},[school?.id,dashboardView]);
 const selectedOffice=officeCards.find(x=>x.id===selectedOfficeId);
 const openSchool=schoolId=>{const target=schools.find(item=>item.id===schoolId);setSelectedOfficeId(target?.officeId||'unassigned');onSelectSchool(schoolId);setDashboardView('school')};
  return <>
   {dashboardView==='offices'&&<><div className="page-title office-page-title"><div><span className="eyebrow">ภาพรวมระบบทั้งหมด</span><h1>สรุปผลสัมฤทธิ์ภาพรวม</h1><p>ข้อมูลรวมทั้งหมด {officeCards.length} สำนักงาน · {overallSchools} โรงเรียน</p></div></div><div className="stat-grid" style={{marginBottom: '24px'}}>{[['นักเรียนทั้งหมดในระบบ', overallStudents, 'คน'],['เข้าสอบและมีผล', overallScored, 'คน'],['คะแนนเฉลี่ยรวม', overallAvg.toFixed(1), '/ 50'],['สอบผ่านรวม', overallRate.toFixed(0), '%']].map(x=><div className="stat card" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="office-grid office-grid-only">{officeCards.map(office=><button type="button" className="office-card card" key={office.id} onClick={()=>{setSelectedOfficeId(office.id);setDashboardView('schools');if(office.schools.length&&!office.schools.some(item=>item.id===school?.id))onSelectSchool(office.schools[0].id)}}><div className="office-card-icon"><School/></div><div className="office-card-title"><b>{office.name}</b><small>{office.schools.length} โรงเรียน · {office.rooms} ห้องเรียน</small></div><strong>{office.students}<small> นักเรียน</small></strong><div className="office-card-metrics"><span>เฉลี่ย <b>{office.avg.toFixed(1)}</b></span><span>ผ่าน <b>{office.rate.toFixed(0)}%</b></span></div></button>)}</div><div className="dashboard-insights-head"><div><span className="eyebrow">ติดตามผู้เรียน</span><h2>ข้อมูลเด็กที่ควรรู้</h2><p>แสดงสูงสุด 20 รายการต่อหมวด โดยไม่ดาวน์โหลดข้อมูลนักเรียนทั้งหมด</p></div><div className="insight-office-filter"><small>กรองตามสำนักงาน</small><Select value={insightOffice} onChange={setInsightOffice}><option value="">สำนักงานทั้งหมด</option>{offices.map(office=><option key={office.id} value={office.id}>{office.name}</option>)}{schools.some(s=>!s.officeId)&&<option value="unassigned">ยังไม่ระบุสำนักงาน</option>}</Select></div></div>{insightError?<div className="card insight-error"><AlertCircle/>{insightError}</div>:insightLoading?<div className="card insight-loading"><Clock3/>กำลังสรุปข้อมูลเด็ก...</div>:<div className="insight-grid">
   <div className="card insight-panel attention"><div className="insight-panel-head"><span><AlertCircle/><b>เด็กที่ต้องติดตาม</b></span><strong>{insights.attention.length}</strong></div><div className="insight-list">{insights.attention.map(item=><button key={`${item.session_id}-${item.student_id}`} onClick={()=>openSchool(item.school_id)}><span><b>{item.full_name}</b><small>{item.school_name} · {item.classroom_name} · เลขที่ {item.student_no}</small></span><em className={item.status}>{item.status==='absent'?'ขาดสอบ':item.status==='pending'?'รอคะแนน':`${item.score} คะแนน`}</em></button>)}{!insights.attention.length&&<p>ไม่พบเด็กที่ต้องติดตาม</p>}</div></div>
   <div className="card insight-panel outstanding"><div className="insight-panel-head"><span><CheckCircle2/><b>เด็กผลงานดี</b></span><strong>{insights.outstanding.length}</strong></div><div className="insight-list">{insights.outstanding.map(item=><button key={`${item.session_id}-${item.student_id}`} onClick={()=>openSchool(item.school_id)}><span><b>{item.full_name}</b><small>{item.school_name} · {item.classroom_name}</small></span><em>{item.score} คะแนน · {item.time_value||'—'}</em></button>)}{!insights.outstanding.length&&<p>ยังไม่มีผลคะแนน</p>}</div></div>
   <div className="card insight-panel improve"><div className="insight-panel-head"><span><LayoutDashboard/><b>ห้องที่ควรพัฒนา</b></span><strong>{insights.roomsToImprove.length}</strong></div><small className="insight-rule">ผู้ผ่านเกณฑ์ต่ำกว่า 60% หรือยังไม่มีผลสอบ</small><div className="insight-list">{insights.roomsToImprove.map(item=><button key={item.classroom_id} onClick={()=>openSchool(item.school_id)}><span><b>{item.classroom_name}</b><small>{item.school_name} · เข้าคะแนน {item.scored}/{item.students} คน</small></span><em className={Number(item.scored)===0?'pending':''}>{Number(item.scored)===0?'ยังไม่มีคะแนน':`${item.pass_percent}%`}</em></button>)}{!insights.roomsToImprove.length&&<p>ทุกห้องมีผู้ผ่านเกณฑ์อย่างน้อย 60%</p>}</div></div>
   <div className="card insight-panel recent"><div className="insight-panel-head"><span><Clock3/><b>กิจกรรมล่าสุด</b></span><strong>{insights.recent.length}</strong></div><div className="insight-list">{insights.recent.map(item=><button key={item.session_id} onClick={()=>openSchool(item.school_id)}><span><b>{item.school_name}</b><small>{item.classroom_name} · {item.test_name} · {item.result_count} ผลสอบ</small></span><em>{item.test_date||'—'}</em></button>)}{!insights.recent.length&&<p>ยังไม่มีกิจกรรม</p>}</div></div>
  </div>}</>}
  {dashboardView==='schools'&&selectedOffice&&<><div className="page-title drill-page-title"><div><span className="eyebrow">สำนักงานที่รับผิดชอบ</span><h1>{selectedOffice.name}</h1><p>{selectedOffice.schools.length} โรงเรียน · {selectedOffice.rooms} ห้องเรียน · นักเรียน {selectedOffice.students} คน</p></div><button type="button" className="button" onClick={()=>{setDashboardView('offices');setSelectedOfficeId(null)}}><ChevronLeft/>สำนักงานทั้งหมด</button></div><div className="card office-schools"><div className="card-head"><div><b>โรงเรียนใน {selectedOffice.name}</b><small>เลือกโรงเรียนเพื่อดูภาพรวมผลการประเมินรายห้อง</small></div><span className="school-count">{selectedOffice.schools.length} โรงเรียน</span></div><div className="office-school-list">{selectedOffice.schools.map(item=>{const summary=summarizeSchool(item);return <button type="button" key={item.id} onClick={()=>{onSelectSchool(item.id);setDashboardView('school')}}><span><School/><b>{item.name}{(item.year||item.term)?' ('+(item.term?'เทอม '+item.term:'')+(item.term&&item.year?' ':'')+(item.year?'ปี '+item.year:'')+')':''}</b></span><small>{summary.rooms} ห้อง · นักเรียน {summary.students} คน</small></button>})}</div>{!selectedOffice.schools.length&&<div className="office-empty">ยังไม่มีโรงเรียนในสำนักงานนี้</div>}</div></>}
  {dashboardView==='school'&&<><div className="page-title drill-page-title"><div><span className="eyebrow">{selectedOffice?.name||'ภาพรวมโรงเรียน'}</span><h1>ผลสัมฤทธิ์การเรียนรู้</h1><p>{school?.name} · ข้อมูลล่าสุดจาก {classes.length} ห้องเรียน</p></div><button type="button" className="button" onClick={()=>setDashboardView('schools')}><ChevronLeft/>โรงเรียนทั้งหมด</button></div>
  <div className="stat-grid">{[['นักเรียนทั้งหมด',stats.all,'คน'],['เข้าสอบ',stats.present,'คน'],['คะแนนเฉลี่ย',stats.avg.toFixed(1),'/ 50'],['ผ่านเกณฑ์รายบุคคล',stats.rate.toFixed(0),'%']].map(x=><div className="stat card" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div>
  <div className="card outcome-card">
   <div className="card-head outcome-head"><div><b>จำนวนนักเรียนและผลสอบรายห้อง</b><small>อ้างอิงผลการทดสอบครั้งล่าสุด · ภาคเรียนที่ {school?.term}/{school?.year}</small></div><div className="outcome-legend"><span><i className="pass"/>ผ่าน</span><span><i className="fail"/>ไม่ผ่าน</span><span><i className="absent"/>ขาดสอบ</span><span><i className="pending"/>รอคะแนน</span></div></div>
   <div className="outcome-chart">{classes.map(c=>{
    const percent=value=>c.students?value/c.students*100:0;
    return <div className="outcome-row" key={c.name}>
     <div className="outcome-class"><b>{c.name}</b><small>{c.students} คน · ทดสอบ {c.tests} ครั้ง</small></div>
     <div className="outcome-bar" aria-label={`${c.name} ผ่าน ${c.passed} ไม่ผ่าน ${c.failed} ขาดสอบ ${c.absent}`}>
      {c.passed>0&&<i className="pass" style={{width:`${percent(c.passed)}%`}} title={`ผ่าน ${c.passed} คน`}>{c.passed}</i>}
      {c.failed>0&&<i className="fail" style={{width:`${percent(c.failed)}%`}} title={`ไม่ผ่าน ${c.failed} คน`}>{c.failed}</i>}
      {c.absent>0&&<i className="absent" style={{width:`${percent(c.absent)}%`}} title={`ขาดสอบ ${c.absent} คน`}>{c.absent}</i>}
      {c.pending>0&&<i className="pending" style={{width:`${percent(c.pending)}%`}} title={`รอคะแนน ${c.pending} คน`}>{c.pending}</i>}
     </div>
     <div className="outcome-total"><strong>{c.students}</strong><small>คน</small></div>
    </div>})}</div>
  </div></>}
 </>;
}

export default Dashboard;
